server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4006
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

          ## REST client sends http://localhost:4004/api/patients
          ## rewrites the request in a way that it can call the internal request
          ## http://patient-service:4000/patients (patient service)

        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath= /api-docs/patients, /v3/api-docs
          ## http://localhost:4004/api-docs/patients  > rest client
          ## http://patient-service:4000/v3/api-docs > gateway

        - id: api-docs-auth-route
          uri: http://auth-service:4006
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath= /api-docs/auth, /v3/api-docs