PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe Wee",
  "email": "al@gmail.com",
  "address": "180 Lisbon St Manila",
  "dateOfBirth": "1991-03-03"
}